variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: "noninteractive"

stages:
  - lint
  - scan
  - build
  - test
  - publish
  - pages

include:
  - project: "ska-telescope/templates-repository"
    file: 
     - "gitlab-ci/includes/python.gitlab-ci.yml"
     - "gitlab-ci/includes/docs.gitlab-ci.yml"
     - "gitlab-ci/includes/finaliser.gitlab-ci.yml"
     - "gitlab-ci/includes/release.gitlab-ci.yml"

python-lint:
  image: ubuntu:24.04
  stage: lint
  tags:
    - ${SKA_DEFAULT_RUNNER}
  before_script:
    - apt-get -y update
    - apt-get -y install make python3 pipx git
    - pipx ensurepath && export PATH=$PATH:~/.local/bin 
    - 'make help | grep python-lint'
    - pipx install poetry
    - poetry config virtualenvs.in-project true
    - poetry config virtualenvs.create true
    - poetry install --all-extras
  script:
    - make python-lint
  artifacts:
    paths:
      - build/
    when: always

