variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: "noninteractive"

stages:
  - lint
  - scan
  - build
  - test
  - publish
  - pages

# Include CI templates
include:
  - project: "ska-telescope/templates-repository"
    file: 
     - "gitlab-ci/includes/python.gitlab-ci.yml"
     - "gitlab-ci/includes/docs.gitlab-ci.yml"
     - "gitlab-ci/includes/finaliser.gitlab-ci.yml"
     - "gitlab-ci/includes/release.gitlab-ci.yml"

python-test:
  before_script:
    - |
      apt-get update -y && apt-get upgrade -y;
      DEBIAN_FRONTEND="noninteractive" apt-get install -y \
      bison build-essential clang-format-14 cmake doxygen curl \
      wget flex gcc g++ gcovr gfortran git libarmadillo-dev \
      libboost-date-time-dev libboost-filesystem-dev \
      libboost-program-options-dev libboost-python-dev \
      libboost-system-dev libboost-test-dev libboost-all-dev \
      libgsl-dev libcfitsio-dev libfftw3-dev libgtkmm-3.0-dev \
      libhdf5-serial-dev libncurses-dev liblua5.3-dev \
      liblapack-dev libpng-dev libpython3-dev libreadline-dev \
      ninja-build pkg-config pybind11-dev python3 python3-dev \
      python3-h5py python3-numpy python3-pip python3-pytest \
      python3-sphinx python3-sphinx-rtd-theme pipx wcslib-dev;
    - |
      git clone https://github.com/casacore/casacore.git;
      cd casacore && git checkout v3.6.0 && mkdir build && cd build;
      cmake -DBUILD_PYTHON=OFF -DBUILD_TESTING=OFF -DDATA_DIR=/usr/share/casacore/data .. && make -j `nproc` && make -j `nproc` install;
      cd ../.. && rm -rf ./casacore;
    - |
      git clone https://gitlab.com/aroffringa/aoflagger.git;
      cd aoflagger && git checkout b1256de90b00a5a83477274390decd6671cdcd38 && mkdir build && cd build;
      cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr .. && ninja install;
      cd ../.. && rm -rf aoflagger;
    - |
      git clone https://git.astron.nl/RD/idg.git;
      cd idg && git checkout 9ce6fa88b9d746d8d7146c474992aba9b98eb41f && mkdir build && cd build;
      cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DPORTABLE=ON .. && ninja install;
      cd ../../ && rm -rf ./idg;
    - |
      git clone https://git.astron.nl/RD/EveryBeam.git;
      cd EveryBeam && git checkout 0578473cacf64c69bc2e05e15754cf94dd1051b9 && mkdir build && cd build;
      cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3 .. && ninja install;
      cd ../.. && rm -rf ./EveryBeam;
    - |
      git clone https://github.com/lofar-astron/DP3.git;
      cd DP3 && mkdir build && cd build;
      cmake .. && make -j `nproc` && make -j `nproc` install;
      cd ../.. && rm -rf ./DP3;
    - DP3 --version;
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
    - 'make help | grep python-test'
    - pipx install poetry && pipx ensurepath && export PATH=$PATH:~/.local/bin
    - echo "python-build Setting.. poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE"
    - poetry config virtualenvs.in-project true && poetry config virtualenvs.create true
    - echo "python-test - Installing with poetry"
    - time poetry install --all-extras
    - source .venv/bin/activate
