[tool.poetry]
name = "ska-sdp-batch-preprocess"
version = "0.1.0"
description = "SKA Distributed batch preprocessing pipeline"
authors = ["Team HIPPO"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
xradio = "^0.0.30"
ska-sdp-datamodels = {git = "https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels.git", rev = "sp-4385-implement-xradio-converter"}
numpy = "^1.26"
python-casacore = "^3.5.2"
PyYAML = "^6.0.1"

# Install with `poetry install --with docs`
[tool.poetry.group.docs.dependencies]
sphinx = "^7.0.0"
sphinx-rtd-theme = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
