[tool.poetry]
name = "ska_sdp_batch_preprocess"
version = "0.1.0"
description = "SKA Distributed batch preprocessing pipeline"
authors = ["Team HIPPO"]
license = "BSD-3-Clause"
readme = "README.md"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "skao"
url = "https://artefact.skao.int/repository/pypi-internal/simple"
priority = "primary"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
xradio = "^0.0.30"

#The following three libraries are using specific branches to function appropriately, this will be changed and would need updating when the branches are merged or deleted
ska-sdp-datamodels = {git = "https://gitlab.com/ska-telescope/sdp/ska-sdp-datamodels.git", rev = "sp-4385-implement-xradio-converter"}
ska-sdp-func-python = {git = "https://gitlab.com/ska-telescope/sdp/ska-sdp-func-python.git", rev = "hip-975_bug_fixing"}
ska-sdp-func = {git = "https://gitlab.com/ska-telescope/sdp/ska-sdp-func.git"}
#NOTE: Not adding aoflagger right now since it's causing import issues.
#aoflagger = {git = "https://gitlab.com/aroffringa/aoflagger.git"}
ska-telmodel = "^1.17"
numpy = "^1.26"
python-casacore = "^3.5.2"
PyYAML = "^6.0.1"

# Install with `poetry install --with docs`
pytest = "^8.3.2"
[tool.poetry.group.docs.dependencies]
sphinx = "^7.0.0"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.extras]
ska-sdp-func = ["ska-sdp-func"]
ska-sdp-func-python = ["ska-sdp-func-python"]
#aoflagger = ["aoflagger"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

