# Model configuration file, format is provisional.

steps:
  - MsIn:
  - PreFlagger:
  - AOFlagger:
      memorymax: 8.0 # GB
  - Averager:
      timestep: 4
      freqstep: 4
  - MsOut:
      overwrite: true
