# Model configuration file
#
# Schema documentation:
# https://developer.skao.int/projects/ska-sdp-batch-preprocess/en/latest/pipeline.html#configuration-file
# 
# DP3 steps documentation:
# https://dp3.readthedocs.io/en/latest/

steps:
  - MsIn:
  - PreFlagger:
  - AOFlagger:
      memorymax: 8.0 # GB
  - Averager:
      timestep: 4 # averaging factor in time
      freqstep: 4 # averaging factor in frequency
  - MsOut:
      overwrite: true
