# Model configuration file
#
# Schema documentation:
# https://developer.skao.int/projects/ska-sdp-batch-preprocess/en/latest/pipeline.html#configuration-file
# 
# DP3 steps documentation:
# https://dp3.readthedocs.io/en/latest/

steps:
  - MsIn:
  - PreFlagger:
  - AOFlagger:
      memorymax: 8.0 # GB
  - ApplyCal:
      # If the path to the H5Parm file is not absolute, it will be preprended
      # by the --extra-inputs-dir argument passed via the command line
      parmdb: bandpass.h5
  - ApplyCal:
      parmdb: polarisation.h5
  - Averager:
      timestep: 4  # averaging factor in time
      freqstep: 4  # averaging factor in frequency
  - MsOut:
      overwrite: true
